server:
   port: 8099
 
eureka:
  client:
    serviceUrl:
      defaultZone: https://cdf-eureka-sp.herokuapp.com/eureka #http://localhost:8761/eureka/    

 
zuul:
  routes:
     farmacia:
      path: /farmacia-micro-client/**
      url:  https://cdf-farmacia-sp.herokuapp.com/ #http://localhost:8080/ 